name: CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      
      - name: Install dependencies
        run: dart pub get
      
      - name: Verify dependencies
        run: dart pub get --offline
      
      - name: Check code formatting
        run: dart format --output=none --set-exit-if-changed .
        continue-on-error: true
      
      - name: Run static analysis
        run: dart analyze --fatal-infos
        continue-on-error: true
      
      - name: Run tests (unit tests only, excluding test/original_tests/)
        env:
          API_KEYS: test:standard:enhanced:enterprise
          RATE_LIMIT_MAX: 100
          RATE_LIMIT_WINDOW_SEC: 60
        run: |
          dart test --reporter=expanded \
            test/auth_test.dart \
            test/feature_flags_test.dart \
            test/logging_test.dart \
            test/notes_db_test.dart \
            test/notes_test.dart \
            test/notes_validation_test.dart \
            test/performance_test.dart \
            test/rate_limit_test.dart
